// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA61nNNT0ZzgUtVc_FAEckFzRO1RISt6ds',
    appId: '1:318671281005:web:885e995067ec0047bd9864',
    messagingSenderId: '318671281005',
    projectId: 'activ-merit',
    authDomain: 'activ-merit.firebaseapp.com',
    storageBucket: 'activ-merit.appspot.com',
    measurementId: 'G-ZQF3WYH3MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALa9cOk5GB3fmP69JlNVTVf2spNNFs_WI',
    appId: '1:318671281005:android:a65a7211925b144cbd9864',
    messagingSenderId: '318671281005',
    projectId: 'activ-merit',
    storageBucket: 'activ-merit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FyNZxUw0O7PSoDoP9_RB9c6QOQaESDY',
    appId: '1:318671281005:ios:916f94d9096c23bfbd9864',
    messagingSenderId: '318671281005',
    projectId: 'activ-merit',
    storageBucket: 'activ-merit.appspot.com',
    androidClientId: '318671281005-7m3fprd7e7kg1q2olk8a81eb3sj92a2g.apps.googleusercontent.com',
    iosClientId: '318671281005-gpi8d5a7lhj4783v6e3bd2equ2ehtfrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.activmerit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FyNZxUw0O7PSoDoP9_RB9c6QOQaESDY',
    appId: '1:318671281005:ios:916f94d9096c23bfbd9864',
    messagingSenderId: '318671281005',
    projectId: 'activ-merit',
    storageBucket: 'activ-merit.appspot.com',
    androidClientId: '318671281005-7m3fprd7e7kg1q2olk8a81eb3sj92a2g.apps.googleusercontent.com',
    iosClientId: '318671281005-gpi8d5a7lhj4783v6e3bd2equ2ehtfrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.activmerit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA61nNNT0ZzgUtVc_FAEckFzRO1RISt6ds',
    appId: '1:318671281005:web:c0328c1143b16958bd9864',
    messagingSenderId: '318671281005',
    projectId: 'activ-merit',
    authDomain: 'activ-merit.firebaseapp.com',
    storageBucket: 'activ-merit.appspot.com',
    measurementId: 'G-QS3K3D583Y',
  );

}